enable_conv = false

# An example for use different algo/settings in "full" preset
unet_target_module = [
]
unet_target_name = [
  "^(?!.*(ff\\.net|proj)).*input_blocks\\.8\\.1\\..*$", # Layout
  "^(?!.*(ff\\.net|proj)).*output_blocks\\.1\\.1\\..*$" # Style
]
text_encoder_target_module = [
  "CLIPAttention",
]
text_encoder_target_name = [
]